import mongoose from "mongoose";
const candidateSchema = new mongoose.Schema(
  {
    candidateID: {
      type: String,
      required: false,  // Removed unique and required flag if it's autogenerated
    },
    did: {
      type: String,
      required: true,
      unique: true,  // Ensure 'did' is unique
    },
    name: {
      type: String,
      required: true,
    },
    dob: {
      type: String,
      required: true,
    },
    logo: {
      type: String,
      required: true,
    },
    birthplace: {
      type: String,
      required: true,
    },
    role: {
      type: String,
      default: "candidate",
    },
    votes: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

const Candidate = mongoose.model("Candidate", candidateSchema);
export default Candidate;
